name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      # Note: jdk8 is necessary to use javah
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set up build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Compile classes
        run: ./gradlew classes --stacktrace

      - name: Build solver shared libraries using Docker
        run: |
          make solver-libs-docker
          sudo install -m 644 build/lib/libminisat.so /usr/lib
          sudo install -m 644 build/lib/libcadical.so /usr/lib
          sudo install -m 644 build/lib/libcryptominisat5.so /usr/lib

      - name: Build JNI-wrapper shared libraries
        run: |
          make headers libs res

      - name: Build package using Gradle wrapper
        run: ./gradlew build --stacktrace --scan

      - name: Upload to GH Releases
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/lib/libjminisat.so
            build/lib/libjcadical.so
            build/lib/libjcms.so
            build/lib/libminisat.so
            build/lib/libcadical.so
            build/lib/libcryptominisat5.so
